import { readFileSync } from 'node:fs';
import path from 'node:path';
const here = new URL(import.meta.url).pathname.replace(/^\/(?=[A-Za-z]:)/, '');
const root = path.resolve(path.dirname(here), '..');
const html = readFileSync(path.join(root, 'public', 'index.html'), 'utf8');
const js = readFileSync(path.join(root, 'public', 'app.js'), 'utf8');
if (!html.includes('subscriptionContextMenu')) throw new Error('missing subscription context menu');
if (html.includes('id="deleteSubscriptionBtn"')) throw new Error('old visible delete button still present');
if (!js.includes('contextmenu')) throw new Error('missing contextmenu handler');
if (!js.includes('copySelectedSubscriptionLinks')) throw new Error('missing copy action');
console.log('subscription context menu test passed');
